name: Build

# Trigger the workflow's on all PRs but only on pushed tags or commits to
# main/master branch to avoid PRs developed in a GitHub fork's dedicated branch
# to trigger.
on:
  pull_request:
  push:
    branches:
    tags:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      # Keep running even if one variation of the job fail
      fail-fast: false
      matrix:
        # We run this job multiple times with different parameterization
        # specified below, these parameters have no meaning on their own and
        # gain meaning on how job steps use them.
        include:
          - python: 3.5
          - python: 3.6
          - python: 3.7
          - python: 3.8
          - python: 3.9

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        with:
          node-version: '12.x'
        uses: actions/setup-node@v1
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python }}"
      - name: Install dependencies
        run: python -m pip install jupyterlab
      - name: Build the extension
        run: |
          cd ./jupyterlab-server-proxy
          jupyter labextension install .
          jupyter labextension list 2>&1 | grep -ie '@jupyterlab/server-proxy.*OK.*'
          python -m jupyterlab.browser_check
